// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CascadeDelete4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascadeDelete4));
        
        string IMigrationMetadata.Id
        {
            get { return "202007181630507_CascadeDelete4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
